language: python
python:
- '2.6'
script:
- rm -rf .git/
- zip -r plugin.video.sendtokodi.zip *
- git clone https://github.com/firsttris/repository.sendtokodi.git
- cp plugin.video.sendtokodi.zip repository.sendtokodi/plugin.video.sendtokodi/
- cd repository.sendtokodi/
- eval "$(ssh-agent -s)"
- chmod 600 /home/travis/build/deploy_rsa
- ssh-add /home/travis/build/deploy_rsa
- git config user.name "firsttris"
- git config user.email "tristanteufel@googlemail.com"
- git add .
- git commit -m "Travis-CI Update"
- git push
before_install:
- openssl aes-256-cbc -K $encrypted_085db88b3643_key -iv $encrypted_085db88b3643_iv
  -in deploy_rsa.enc -out /home/travis/build/deploy_rsa -d
