language: python
python:
- '3.5'
env:
  global:
    - GH_REF="github.com/firsttris/repository.sendtokodi.git"
    - VERSION=0.0.${TRAVIS_JOB_NUMBER}
script:
- rm -rf .git/
- envsubst < "addon.template.xml" > "addon.xml"
- zip -r plugin.video.sendtokodi-${VERSION}.zip *
- git clone https://github.com/firsttris/repository.sendtokodi.git
- cp addon.xml repository.sendtokodi/plugin.video.sendtokodi/
- cp plugin.video.sendtokodi.zip repository.sendtokodi/plugin.video.sendtokodi/
- cd repository.sendtokodi/
- git add .
- git commit -m "Travis-CI Update"
- git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master > /dev/null 2>&1