language: python
python:
- '2.6'
env:
  global:
    - GH_USER_EMAIL="tristanteufel@googlemail.com"
    - GH_USER_NAME="firsttris"
    - GH_REF="github.com/firsttris/repository.sendtokodi.git"
script:
- rm -rf .git/
- zip -r plugin.video.sendtokodi.zip *
- git clone https://github.com/firsttris/repository.sendtokodi.git
- cp plugin.video.sendtokodi.zip repository.sendtokodi/plugin.video.sendtokodi/
- cd repository.sendtokodi/
- git add .
- git commit -m "Travis-CI Update"
- git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master > /dev/null 2>&1