language: python
python:
  - "2.6"
script:
  - rm -rf .git/
  - zip -r plugin.video.sendtokodi.zip *
  - git clone https://github.com/firsttris/repository.sendtokodi.git
  - cp plugin.video.sendtokodi.zip repository.sendtokodi/plugin.video.sendtokodi/
  - cd repository.sendtokodi/
  - eval "$(ssh-agent -s)"
  - echo "$GH_TOKEN" > deploy_key.pem
  - chmod 600 deploy_key.pem
  - ssh-add deploy_key.pem
  - git config user.name "Travis-CI"
  - git config user.email "travis@teufel-it.de"
  - git add .
  - git commit -m "Travis-CI Update"
  - git push